Device Authorization Grant
thephpleague/oauth2-server pull request #1074
Opened 2019-11-28 09:48 UTC by lucadegasperi

Hello,
Since I needed the device authorization grant for a project I'm working on, I've decided to give a shot at implementing it in a presentable way.

For the most part I copied other grants code where needed and tried to keep the methods and interfaces as similar to what's already implemented as possible.

The interval checking between requests for an access token is currently not implemented, as I think this could be more easily delegated to a framework middleware than implement the logic right inside the package.

Pairing a user identifier with the device code is left outside the scope of this implementation as well.

I've created a laravel passport implementation based off this code that you can find here: https://github.com/lucadegasperi/passport/tree/device-flow

Let's make this grant happen!

2020-01-05 18:40 UTC, lucadegasperi commented
Thanks for the fixes @Sephster, do you think it's good enough to merge now?

2020-01-07 17:56 UTC, Sephster commented
Hi @lucadegasperi - sorry I still have a wee bit more to look at. Specifically around handling of pass checking and response rates. I think this probably does need including so have started to add these in. Thanks for your patience with this.

2020-01-28 21:25 UTC, yovchev commented
Hi, @Sephster I think the rate limiter must be Middleware implementation.

Let me know what you think I will try to get something mocked up soon.

2020-01-30 00:42 UTC, yovchev commented
@Sephster I have mocked up something that uses cache let me know if you will be ok with something like this in the examples composer I started setting up the Middleware and the Rate limiter but I need a way of caching between request. 

If you don't want to include other lib's I can use raw `file_put_contents` to cache between requests

https://github.com/lucadegasperi/oauth2-server/pull/1

2020-02-02 02:55 UTC, yovchev commented
@Sephster I was able to do the example without middleware please see a working example here 

https://github.com/lucadegasperi/oauth2-server/pull/1/commits/3865bace7768e85454398ff6d26cf2568a833867

2020-02-06 21:29 UTC, yovchev commented
I did some extra work on this here if you interested feel free to look and let me know if I can help to get this merged soon.

https://github.com/yovchev/oauth2-server/commits/device-flow

2020-02-07 01:34 UTC, yovchev commented
@Sephster Ignore my previous comments the middleware implementation don't make sense please check this as a possible candidate for handling polling rate https://github.com/yovchev/oauth2-server/commits/device-flow-grant

2020-02-24 19:52 UTC, Sephster commented
@lucadegasperi and @yovchev sorry for the radio silence on this ticket. I have some time coming up this week so will aim to push this through asap. Cheers for your patience.

2020-02-26 10:26 UTC, yovchev commented
No worries @Sephster I will be at hand if I can help with something.

2020-03-31 10:23 UTC, Sephster commented
@yovchev thanks for your time on this. I had a look yesterday and couldn't get the examples to work. I think this is because my system wasn't creating a cache folder as it didn't have permission to do so.

I'm thinking that it might be simpler to just do away with the cache system and instead rewrite the example with a ready made SQLite DB which would probably be easier to maintain. If we went down this route, I'd be ok with just pushing through the device code grant changes and sorting out the examples in a separate PR. 

I will have a look at the changes without the examples to see if we can progress them. Thanks for your patience

2020-06-30 15:12 UTC, AlastairDewar commented
@Sephster I appreciate it's a chaotic time for everyone at the moment. Is there anything that I can do to help get this merged?

2020-06-30 22:10 UTC, Sephster commented
Hi Ally. Thanks for offering to help. There isn't much that can be done at this time to be honest and I just need to find a significant block of time to finish this off as conscious it has been sitting here a good while now. The main issue is I don't want to merge prior to making sure it covers the spec properly. 

To do this I also want to rewrite the examples for Slim 4 so I can easily do some manual testing rather than just read code and tick off all of the points which is time consuming.

I'm hesitant to commit to a date as I have a baby in the house just now so my time isn't as available as it was a few months ago but hoping to get some time to work on this soon. I just can't commit to a firm date at present as don't want to disappoint. Thanks for your offer of help though and I will try my best to get this out the door sooner rather than later.

2020-08-11 10:24 UTC, yovchev commented
Hi, @Sephster congrats on the baby.

Let me know if this is the speck you want to make sure is covered [rfc8628](https://tools.ietf.org/html/rfc8628)
and I will do one run of tests on the latest pull request and reply here any findings.

2021-02-12 13:28 UTC, Bloemendaal commented
Hi!

I've got a question about the given example. The example uses `client_secret` for obtaining a `device_code` and obtaining an `access_token`. However, the standard states that a device should always be treated as a public client, see [RFC8628 Section 5.6](https://tools.ietf.org/html/rfc8628#section-5.6) and [RFC6749 Section 2.1](https://tools.ietf.org/html/rfc6749#section-2.1).

Is the `client_secret` optional?

Let's hope this feature gets implemented soon! 🙌

2021-09-07 15:21 UTC, GreyXor commented
Thank you, very useful! Can I use it in production or are there important things missing?

2021-09-07 15:21 UTC, GreyXor commented
@lucadegasperi Thank you, very useful! Can I use it in production or are there important things missing?

2021-09-07 17:47 UTC, lucadegasperi commented
@GreyXor I do use it in production, but I'm not sure if the spec has changed in the meanwhile. Probably @Sephster has a better understanding of the state of things.

2021-09-08 08:31 UTC, GreyXor commented
@lucadegasperi @Sephster thanks :) do you know if it can be merged soon ?

2021-12-28 13:02 UTC, GreyXor commented
@lucadegasperi @Sephster thanks :) do you know if it can be merged soon ?

2022-09-01 17:55 UTC, ivanleskovar commented
Hi all,

Nice work!

@Sephster when can we expect this can be merged?

2022-09-01 18:02 UTC, Sephster commented
Aiming for next major.

2022-09-13 06:22 UTC, ivanleskovar commented
@Sephster thx.
Any estimate when we can expect it?

2023-11-03 12:23 UTC, modricl commented
@Sephster do you have estimate date for next major?

2023-11-03 12:34 UTC, Sephster commented
Hopefully in the next few weeks. Testing underway now. If you're interested in this grant, I would welcome you giving it a spin

2023-11-18 04:14 UTC, sniper7kills requested changes

2023-11-18 04:14 UTC, sniper7kills commented on src/AuthorizationServer.php
> +    public function completeDeviceAuthorizationRequest(string $deviceCode, string|int $userId): ResponseInterface
```php
public function completeDeviceAuthorizationRequest(string $deviceCode, string|int $userId, bool $approved): ResponseInterface
```

2023-11-18 04:14 UTC, sniper7kills commented on src/AuthorizationServer.php
> +            ->completeDeviceAuthorizationRequest($deviceCode, $userId)
```php
->completeDeviceAuthorizationRequest($deviceCode, $userId, $approved)
```

2023-11-18 04:14 UTC, sniper7kills commented on src/AuthorizationServer.php
> +    }
Testing this out w/ Laravel Passport; Getting the following error: Still a WIP; so unsure if actually a bug/issue.
```
ArgumentCountError: Too few arguments to function League\OAuth2\Server\Grant\DeviceCodeGrant::completeDeviceAuthorizationRequest(), 2 passed in /var/www/html/vendor/league/oauth2-server/src/AuthorizationServer.php on line 160 and exactly 3 expected in file /var/www/html/vendor/league/oauth2-server/src/Grant/DeviceCodeGrant.php on line 125
```

2023-11-18 19:15 UTC, sniper7kills commented on src/AuthorizationServer.php
> +    }
Additionally; should it be returning a ResponseInterface; when in src/Grant/DeviceCodeGrant.php Line #125 returns void; or should that be returning a ResponseInterface instead of void?

2023-11-19 00:40 UTC, sniper7kills commented
@Sephster @lucadegasperi ,

Just finished taking a look and implementing this locally. Beyond the above few comments I was able to get @lucadegasperi passport implementation updated (https://github.com/RunbookSolutions/passport/tree/device-code) and got everything working using a python as the "device".

Great Work Guys!

2024-03-21 15:56 UTC, Sephster commented on src/AuthorizationServer.php
> +    public function completeDeviceAuthorizationRequest(string $deviceCode, string|int $userId): ResponseInterface
Thanks for this suggestion @sniper7kills - I just went to implement it then and looks like I already came to the same conclusion. I'd added an additional argument, `$userApproved` which is pretty much what you suggested. Thank you for taking the time to look at this and thanks for the valuable input

2024-03-21 15:57 UTC, Sephster commented on src/AuthorizationServer.php
> +            ->completeDeviceAuthorizationRequest($deviceCode, $userId)
Great suggestion and incorporated into the branch. Thank you

2024-03-21 16:23 UTC, Sephster commented on src/AuthorizationServer.php
> +    }
You are not the first person to have suggested this so I might change this. My thinking was that unlike the auth code grant, we aren't passing calls around and redirecting etc so we could just call the method directly. I think I might need to revisit this though. I'm going to get the first release candidate out today, then will look at how this works with Passport to get a level of confidence on the implementation, and perhaps change it if I run into problems. Cheers

2024-03-21 16:46 UTC, Sephster approved these changes

2024-03-21 16:51 UTC, merged