Fix confusing auth behavior when used with a common .htaccess pattern
thephpleague/oauth2-server pull request #1170
Opened 2020-12-08 23:37 UTC by symbioquine

**Why:** It is common for .htaccess files - including the default one
provided by Drupal Core - to coerce the `Authorization` header to the
empty string if not specified by the client. Without this fix, that
results in a `WWW-Authenticate: Basic` header response which causes
the browser to show a useless basic authentication dialog.

For more info see https://github.com/thephpleague/oauth2-server/issues/1162

2020-12-10 16:44 UTC, Sephster requested changes

2020-12-10 16:44 UTC, Sephster commented on src/Exception/OAuthServerException.php
> +        if ($this->errorType === 'invalid_client' && $this->requestHasAuthorizationHeader()) {
```suggestion
        if ($this->errorType === 'invalid_client' && !empty($this->serverRequest->getHeader('Authorization'))) {
```

We could remove the function and replace with the line change above I think

2020-12-10 17:05 UTC, symbioquine commented on src/Exception/OAuthServerException.php
> +        if ($this->errorType === 'invalid_client' && $this->requestHasAuthorizationHeader()) {
I don't think so. The case we're trying to detect has a *non-empty* array containing a single empty string.

It would need to be something more like;

```patch
-        if ($this->errorType === 'invalid_client' && $this->requestHasAuthorizationHeader()) {
+        if ($this->errorType === 'invalid_client' && !empty($this->serverRequest->getHeader('Authorization')) && !empty($this->serverRequest->getHeader('Authorization')[0])) {
```

I think you suggested putting it out in a separate function on https://github.com/thephpleague/oauth2-server/issues/1162 because the above gets a bit unwieldy and didn't leave a good place to include an explanatory comment for this case.

Likely irrelevant, but if the code didn't need to be written to support earlier versions of PHP, it could be written more tersely (cryptically?) along these lines;

```php
$headers = $this->serverRequest->getHeaders();

if ($this->errorType === 'invalid_client' && !empty($headers['Authorization'][0] ?? '')) {
```

2020-12-10 17:53 UTC, Sephster commented on src/Exception/OAuthServerException.php
> +        if ($this->errorType === 'invalid_client' && $this->requestHasAuthorizationHeader()) {
Ahh sorry. I thoght it returned an empty array. Cheers for the explanation. Makes sense

2020-12-11 12:09 UTC, Sephster commented
Looks great thanks @symbioquine - I've updated the changelog and happy to merge. Thank you

2020-12-11 12:10 UTC, merged