Use key as string without a temporary file
thephpleague/oauth2-server pull request #1180
Opened 2020-12-24 19:36 UTC by ssigwart

- Addresses thephpleague/oauth2-server#1007
- This allows you to use a private key from a string without writing to a temporary file.  For security reasons, I'd rather not have the key written to disk on the server.

2021-03-14 17:01 UTC, Sephster requested changes
I think we are removing the ability to use a password against the private key here. Is it possible to change this to accommodate this? Thanks for your submission.

2021-03-14 18:41 UTC, ssigwart reviewed
Thanks for looking @Sephster.  I think my change addresses your comment.

2021-03-14 18:41 UTC, ssigwart commented on src/Entities/Traits/AccessTokenTrait.php
> +            $this->privateKey->getKey(),
The constructor for `CryptKey` handles it for a file.  However, it looks like I was missing the ability for a string key, so I added that.

2021-04-20 14:28 UTC, ssigwart commented
@Sephster, is there anything I should do to get this merged?

2021-06-25 14:56 UTC, ssigwart commented
@Sephster, there are merge conflicts now.  Should I rebase and resolve them?

2021-06-25 15:14 UTC, Sephster commented
That would be appreciated cheers. I've been tidying up a personal project but hoping to get back to this within the week. Thanks very much

2021-06-25 17:03 UTC, ssigwart commented
Thanks, @Sephster.  I rebased it and fixed the conflicts.

2021-06-25 18:53 UTC, eugene-borovov commented on src/CryptKey.php
> +            $this->key = InMemory::plainText($keyPath, $this->passPhrase ?? '');
The `CryptKey` class is a DTO with fast fail validation. You should store key content instead of create `Lcobucci\JWT\Signer\Key` instance. `CryptKey` and  `Lcobucci\JWT\Signer\Key` are the same. Why not use the `Lcobucci\JWT\Signer\Key` directly?

2021-06-25 20:26 UTC, ssigwart commented on src/CryptKey.php
> +            $this->key = InMemory::plainText($keyPath, $this->passPhrase ?? '');
Hi, @eugene-borovov.  Thanks for reviewing, but I don't really understand your comment.  `CryptKey` is not a subclass of `Lcobucci\JWT\Signer\Key`, so I don't know why you said they are the same.

I could store `$contents` as the class variable instead of `$key`.  It seems like it would be more efficient to once have to create the key object once though.  Sorry if I'm missing something obvious here.

2021-06-26 03:23 UTC, eugene-borovov commented on src/CryptKey.php
> +            $this->key = InMemory::plainText($keyPath, $this->passPhrase ?? '');
Hi, @ssigwart.
I apologize for my confused question. I wanted to say that it is better to create `Lcobucci\JWT\Signer\Key` immediately before using it in `lcobucci\jwt`. Otherwise, an extra dependency is created on `lcobucci\jwt`, which increases the coherence with the external library. Do you agree?

2021-06-26 03:41 UTC, ssigwart commented on src/CryptKey.php
> +            $this->key = InMemory::plainText($keyPath, $this->passPhrase ?? '');
Thanks, @eugene-borovov.  It sounds like you want as few places as possible referencing `lcobucci\jwt`, so I updated it to save just the key contents.  Then I updated the places that used the keys to set up the `Lcobucci\JWT\Signer\Key` object since those already were using `lcobucci\jwt`.

2021-07-08 05:20 UTC, eugene-borovov approved these changes

2021-07-10 11:04 UTC, Sephster commented
@ssigwart would it be possible for you to resolve the conflict? I tried to do this myself but don't have write access to your branch. There is also a trailing comma on line 80 of the BearerToken file which is causing issues in PHP 7.2. Thank you

2021-07-10 13:41 UTC, ssigwart commented
@Sephster, I fixed the trailing comma and rebased to fix the conflict.  Thanks!

2021-07-12 07:34 UTC, Sephster approved these changes

2021-07-12 07:38 UTC, merged

2021-07-12 07:38 UTC, Sephster commented
Thanks @ssigwart - looks great.