Add switch to prevent revoking of refresh tokens.
thephpleague/oauth2-server pull request #1189
Opened 2021-02-11 15:39 UTC by janhopman-nhb

Hi,
Recently we (my colleagues and i) came across a specific use case in our software which uses oauth2-server where we needed to prevent refresh tokens to be revoked after requesting a new access token. We looked at the ouath rfc and read that this behaviour is allowed according to the spec. I've gone ahead and implemented the change in this pull request. See below for references to the specific information on refresh tokens in the rfc.

According to [section 1.5](https://tools.ietf.org/html/rfc6749#section-1.5), issuing a new refresh token is optional (see step H).
Also according to [section 4.1](https://tools.ietf.org/html/rfc6749#section-4.1) which describes the authorization code grant type, the refresh token is optional (see step E).
Finally according to [section 6](https://tools.ietf.org/html/rfc6749#section-6) (Refreshing an Access token), in the last paragraph it states that the server MAY issue a new refresh token.
And also states that the server MAY revoke the old refresh token.

Hoping someone can take a look at this, any suggestions and/or feedback, would be much appreciated!

2021-05-29 12:39 UTC, Sephster commented
Thanks @janhopman-nhb  - is there a way to implement this that won't break BC? If not, I think we will leave this PR for now. I also want to change refresh tokens so they don't have an expiration as this isn't part of the spec so would like to roll that into one as part of a major release. Thanks

2021-05-31 12:38 UTC, janhopman-nhb commented
Hi @Sephster, Thank you for your reply! We will have a look if we can implement without breaking BC.

2021-05-31 13:22 UTC, janhopman-nhb commented
Hi @Sephster, is it possible to approve running the workflows by any chance?

2021-05-31 13:26 UTC, Sephster commented
Done, thanks!

2021-05-31 13:33 UTC, janhopman-nhb commented
@Sephster Really sorry for bothering you... 😅  Just fixed the bc issue i think, but the workflows need to be triggerd again to confirm...

2021-05-31 19:20 UTC, Sephster requested changes
Thank you - a few comments but this is looking good thanks!

2021-05-31 19:20 UTC, Sephster commented on src/AuthorizationServer.php
> +        bool $revokeRefreshTokens = true
Can we remove this from the constructor? I'm already conscious that the constructors are quite heavy in the lib. Lets set the class variable to true on init instead and remove this from the constructor. Anyone that wants to change it can just call the setter function. Thank you

2021-05-31 19:20 UTC, Sephster commented on tests/Grant/RefreshTokenGrantTest.php
> +        $grant->setRevokeRefreshTokens(true);
Would you be able to add in a test to check that when we revoke a token, it is revoked and when we don't, we are still able to use it?

2021-06-01 07:26 UTC, janhopman-nhb commented on tests/Grant/RefreshTokenGrantTest.php
> +        $grant->setRevokeRefreshTokens(true);
Thank you for your comments, going to have a look if i can get this done!

2021-06-03 21:38 UTC, Sephster approved these changes

2021-06-03 21:41 UTC, Sephster commented
LGTM - thank you for your work on this @janhopman-nhb

2021-06-03 21:42 UTC, merged