Rfc8252 compliance
thephpleague/oauth2-server pull request #1203
Opened 2021-03-15 20:57 UTC by exeba

#1188

2021-03-15 21:47 UTC, Sephster requested changes
Please can you add an update for the CHANGELOG.md file as well? Thanks for this.

2021-03-15 21:47 UTC, Sephster commented on src/Grant/AbstractGrant.php
> -            $this->getEmitter()->emit(new RequestEvent(RequestEvent::CLIENT_AUTHENTICATION_FAILED, $request));
The emitters need to be retained as we don't want to remove functionality

2021-03-15 21:47 UTC, Sephster commented on src/RedirectUriValidators/Rfc8252RedirectUriValidator.php
> +class Rfc8252RedirectUriValidator
It would be good to have this implement an interface. I also think this class should probably just be called `RedirectUriValidator` as I don't think we need to differentiate with the RFC number.

2021-03-15 21:47 UTC, Sephster commented on src/RedirectUriValidators/Rfc8252RedirectUriValidator.php
> +    public function __construct(ClientEntityInterface $client)
Please add doc blocks in the same style as the rest of the codebase.

2021-03-15 21:47 UTC, Sephster commented on src/RedirectUriValidators/Rfc8252RedirectUriValidator.php
> +    public function validateRedirectUri(string $redirectUri)
Please remove scalar typehints just to keep consistency with the rest of the codebase.

2021-03-15 21:47 UTC, Sephster commented on src/RedirectUriValidators/Rfc8252RedirectUriValidator.php
> +    private function matchFullUri(string $redirectUri)
Maybe rename this to `matchExactUri` to make it clearer what is happening.

2021-04-09 11:14 UTC, marc-mabe commented on src/RedirectUriValidators/RedirectUriValidator.php
> +            && (\in_array($parsedUri['host'], ['127.0.0.1', '[::1]'], true));
At least on IPv4 all addresses beginning with `127.` are loopback addresses.

2021-04-09 11:44 UTC, exeba commented on src/RedirectUriValidators/RedirectUriValidator.php
> +            && (\in_array($parsedUri['host'], ['127.0.0.1', '[::1]'], true));
It seems to me that the RFC allows only 127.0.0.1 and ::1, maybe I can change the name in isLoopbackUri so that is less misleading?

2021-04-09 16:14 UTC, marc-mabe commented on src/RedirectUriValidators/RedirectUriValidator.php
> +            && (\in_array($parsedUri['host'], ['127.0.0.1', '[::1]'], true));
A comment would already be very helpful ;)

2021-04-17 12:02 UTC, Sephster requested changes
Thanks @exeba and apologies for taking a while to get around to reviewing this. I've added some requests for changes. Thanks for your efforts with this.

2021-04-17 12:02 UTC, Sephster commented on src/RedirectUriValidators/RedirectUriValidator.php
> +    private function getClientRedirectUris()
We already have a function got getting client redirect uris on the client object so it isn't immediately clear from the function name why this is different. I think this function could benefit from a rename to improve clarity. Thank you

2021-05-21 13:45 UTC, marc-mabe commented
@Sephster What is the state of this?

2021-05-29 11:35 UTC, Sephster commented on src/RedirectUriValidators/RedirectUriValidator.php
> +    public function __construct(ClientEntityInterface $client)
Implementation changed so marking as resolved.

2021-05-29 11:38 UTC, Sephster commented on src/RedirectUriValidators/RedirectUriValidator.php
> +    private function allowDifferentPort(array $parsedUrl)
Great rename. Thank you

2021-05-29 12:04 UTC, Sephster approved these changes

2021-05-29 12:05 UTC, Sephster commented
This looks great. Will merge this in as soon as I've fixed the merge conflict. Thanks so much @exeba

2021-05-29 12:37 UTC, merged