Validate key with phpseclib3
thephpleague/oauth2-server pull request #1215
Opened 2021-04-19 18:51 UTC by eugene-borovov

Added key validation using phpseclib. RSA and EC keys are supported. In the future, I would like to make separate types for Public and Private keys to check this aspect as well.

Fixes #1214

2021-05-15 22:10 UTC, Sephster commented
Is there a way to make this a non-BC change? If not, I think we'd need to target this for v9. Also would be good to do something when we encounter an exception. Thank you for this

2021-05-16 04:19 UTC, Spomky commented
You don't need PHPSECLIB at all (which is a big fat dep from my POV). As openssl is already required, you just need to get the key details to ensure it is valid: https://www.php.net/manual/fr/function.openssl-pkey-get-details.php

2021-05-16 14:46 UTC, eugene-borovov commented
I returned the RSA_KEY_PATTERN constant that the backward compatibility check passed.

2021-05-17 03:37 UTC, eugene-borovov commented
Version of the key verification using OpenSSL.  @Sephster , maybe we should try OpenSSL directly?

```php
function isValidKey($contents, $passPhrase)
{
    $pkey = openssl_pkey_get_private($contents, $passPhrase) ?: openssl_pkey_get_public($contents);
    if ($pkey === false) {
        return false;
    }
    $details = openssl_pkey_get_details($pkey);

    return $details !== false && in_array(
        $details['type'] ?? -1,
        [OPENSSL_KEYTYPE_RSA, OPENSSL_KEYTYPE_EC],
        true
    );
}
```

2021-05-29 11:24 UTC, Sephster requested changes
Looks good to me. Thanks very much for making this change. If we could use the native `is_file()` and add in some basic tests, this should be good to go. Thanks so much for your efforts with this. Much appreciated!

2021-05-29 11:24 UTC, Sephster commented on src/CryptKey.php
> +    private function isFilePath()
There it the native `is_file()` function that we could use. I think this would be preferable over rolling our own method unless you can see any issues?

2021-05-29 15:41 UTC, Spomky commented
Excellent!

Looks way more clear and efficient compared to pure PHP functions.
Well done @eugene-borovov!

2021-05-31 04:54 UTC, eugene-borovov commented on src/CryptKey.php
> +    private function isFilePath()
The purpose of this method is to show the key storage type, but I haven't found any use for it outside of the class. So I removed it completely.

2021-05-31 19:30 UTC, Sephster approved these changes

2021-05-31 19:30 UTC, Sephster commented
Thank you @eugene-borovov  - looks great. Happy to merge!

2021-05-31 19:30 UTC, merged