Checking the URI before matching
thephpleague/oauth2-server pull request #1237
Opened 2021-07-12 17:15 UTC by eugene-borovov

A redirect URI without scheme causes an error.

2021-07-15 08:57 UTC, Sephster requested changes

2021-07-15 08:57 UTC, Sephster commented on src/RedirectUriValidators/RedirectUriValidator.php
> +        $redirectUri = \filter_var($redirectUri, FILTER_VALIDATE_URL);
This doesn't only check for `http` schemas. It also allows `ftp`, `mailto` etc. I think we  need to be more specific with this check if possible.

2021-07-15 09:27 UTC, eugene-borovov commented on src/RedirectUriValidators/RedirectUriValidator.php
> +        $redirectUri = \filter_var($redirectUri, FILTER_VALIDATE_URL);
This is only the first stage of checking the URL to make sure that it is correct. Then the mapping is performed with the redirect URL. Without this check, an incorrect URL will cause an error in the schema checking code.

2021-07-15 15:59 UTC, Sephster commented on src/RedirectUriValidators/RedirectUriValidator.php
> +        $redirectUri = \filter_var($redirectUri, FILTER_VALIDATE_URL);
Could you paste an example of the error you are getting? Thank you

2021-07-16 03:23 UTC, eugene-borovov commented on src/RedirectUriValidators/RedirectUriValidator.php
> +        $redirectUri = \filter_var($redirectUri, FILTER_VALIDATE_URL);
I have got an error like this:
```
Undefined index: scheme
 /opt/project/src/RedirectUriValidators/RedirectUriValidator.php:69
 /opt/project/src/RedirectUriValidators/RedirectUriValidator.php:49
 /opt/project/src/Grant/AbstractGrant.php:288
 /opt/project/src/Grant/AuthCodeGrant.php:269
 /opt/project/tests/Grant/AuthCodeGrantTest.php:394
```

You can reproduce by changing `redirect_uri` in query parameter to `localhost` or something without scheme.
I used `\LeagueTests\Grant\AuthCodeGrantTest::testValidateAuthorizationRequestBadRedirectUriString`

2021-07-19 04:30 UTC, eugene-borovov commented on src/RedirectUriValidators/RedirectUriValidator.php
> +        $redirectUri = \filter_var($redirectUri, FILTER_VALIDATE_URL);
> This doesn't only check for `http` schemas. It also allows `ftp`, `mailto` etc. I think we need to be more specific with this check if possible.

I added http schema validation. So only valid urls could be check or add as allowed redirect urls.

2021-07-25 21:51 UTC, boesing commented
Oh, haven't seen this before raising my issue.
This relates to #1239

2021-07-25 22:23 UTC, Spomky commented
URNs shall be accepted too.  See example at https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-desktop-app-registration

The URN `urn:ietf:wg:oauth:2.0:oob` won't pass this validation.

2021-07-26 04:16 UTC, eugene-borovov commented
I fixed the `isLoopbackUri` check and remove scheme restrictions. So URNs and private URI schemes and redirect path should pass. The host and/or path are required for the correct URL.

2021-07-26 04:42 UTC, eugene-borovov commented
https://datatracker.ietf.org/doc/html/rfc6749#section-3.1.2

> The redirection endpoint URI MUST be **an absolute URI** as defined by
   [[RFC3986] Section 4.3](https://datatracker.ietf.org/doc/html/rfc3986#section-4.3).  The endpoint URI MAY include an
   "application/x-www-form-urlencoded" formatted (per Appendix B) query
   component ([RFC3986] Section 3.4), which MUST be retained when adding
   additional query parameters.  The endpoint URI MUST NOT include a
   fragment component.

So scheme is required.

2021-07-27 07:54 UTC, Sephster commented
I see Microsoft mentioning urns but don't see anything in the official specs about urn support. Just custom app schemes. We always follow the official RFCs so I'm not concerned with urns at this time but if someone can find info in an oauth RFC that specifies we should support urns, we will of course include this.

2021-07-27 08:24 UTC, Spomky commented
Actually, URNs are more likely used for native apps. 
See also the Google Documentation at https://developers.google.com/youtube/v3/live/guides/auth/installed-apps

2021-07-27 09:00 UTC, eugene-borovov commented
https://datatracker.ietf.org/doc/html/rfc6749#section-3.1.2

> The redirection endpoint URI MUST be an absolute URI as defined by [RFC3986] Section 4.3. 

https://datatracker.ietf.org/doc/html/rfc3986#section-1.1.3

> A URI can be further classified as a locator, a name, or both.  The term "Uniform Resource Locator" (URL) refers to the subset of URIs that, in addition to identifying a resource, provide a means of locating the resource by describing its primary access mechanism (e.g., its network "location").  The term "Uniform Resource Name" (URN) has been used historically to refer to both URIs under the "urn" scheme [RFC2141], which are required to remain globally unique and persistent even when the resource ceases to exist or becomes unavailable, and to any other URI with the properties of a name.

https://datatracker.ietf.org/doc/html/rfc3986#section-3

>    The following are two example URIs and their component parts:

         foo://example.com:8042/over/there?name=ferret#nose
         \_/   \______________/\_________/ \_________/ \__/
          |           |            |            |        |
       scheme     authority       path        query   fragment
          |   _____________________|__
         / \ /                        \
         urn:example:animal:ferret:nose


So URNs can also be redirect URIs.

2021-07-27 09:01 UTC, Sephster commented
I'm not sure this is more common but would happily be proved wrong. As I said before though, I would really want to see something about URNs in the Oauth specs before committing to this. If it is an official implementation, recommended by the IETF then we should support this. Is there any spec out there specifying this?

2021-07-27 09:06 UTC, Sephster commented
Thanks @eugene-borovov and @Spomky for clarifying this

2021-07-27 09:16 UTC, eugene-borovov commented
By the way, the main purpose of this PR is to fix the `isLoopbackUri` method and add some verification for redirect URI. The URN discussion is a side effect of the too strict validation rules that I gave initially.

2021-07-27 10:14 UTC, Spomky commented
> [...] , I would really want to see something about URNs in the Oauth specs before committing to this.

The spec refers to URIs, which includes URLs and URNs right?
https://en.m.wikipedia.org/wiki/Uniform_Resource_Identifier

2021-08-05 05:48 UTC, Spomky commented on tests/RedirectUriValidators/RedirectUriValidatorTest.php
> +
These new tests could be simplified using a dataProvider

2021-08-05 06:24 UTC, eugene-borovov commented on tests/RedirectUriValidators/RedirectUriValidatorTest.php
> +
Good point. I added dataProvider. Have I listed all the cases? Maybe you know more?

2021-08-05 06:39 UTC, Spomky commented on tests/RedirectUriValidators/RedirectUriValidatorTest.php
> +
Excellent. what a quick update!

2021-08-05 06:42 UTC, Spomky commented on tests/RedirectUriValidators/RedirectUriValidatorTest.php
> +
Is there somewhere a test with a valid url e.g. `http://example.com:8080/endpoint?foo=BAR`

2021-08-05 06:53 UTC, eugene-borovov commented on tests/RedirectUriValidators/RedirectUriValidatorTest.php
> +
I have added more valid URLs for clarity.

2022-04-06 22:22 UTC, Sephster commented
Thank you for this PR @eugene-borovov and I'm sorry I didn't get a chance to push this through. Since this was submitted a newer PR was proposed (#1274) which I think provides a more elegant solution as it relies on the league/uri package to handle parsing. For this reason, I'm going to close this PR but wanted to thank you for trying to resolve the issue.

2022-04-06 22:22 UTC, closed without merging

2022-04-07 01:58 UTC, eugene-borovov commented
@Sephster #1274 resolves only loopback URI. This PR resolves all redirect URI validation. These are different branches of the validate algorithm. This PR allows to use URN as redirect URI in addition.

2022-04-07 21:16 UTC, Sephster commented
thanks for the quick reply @eugene-borovov. I added in some further tests to main, based on yours, to ensure we are able to accept custom schemes and urns. I think that the solution that has been merged does ensure all valid uris are accepted because it is using the league/uri package. If an invalid uri is passed (poorly formed rather than not pre-registered), the library will throw an exception. Thank you again for your efforts here and sorry I didn't merge it this time.

2022-04-08 04:13 UTC, eugene-borovov commented
@Sephster I`d suggested to use URI validation in constructor. So on loopback analyze step you have valid URI and test only the host. Also this prevents using no-URI strings as redirect_uri as in the issue https://github.com/thephpleague/oauth2-server/issues/1239.