Bump psr/http-message version
thephpleague/oauth2-server pull request #1339
Opened 2023-04-18 17:11 UTC by erikn69

2023-05-05 13:37 UTC, parallels999 approved these changes

2023-05-05 13:38 UTC, parallels999 commented
@Sephster ping

2023-05-15 14:46 UTC, Sephster requested changes

2023-05-15 14:46 UTC, Sephster commented on composer.json
> +        "psr/http-message": "^1.0.1 || ^2.0",
Could we just change this to use 2.0? Looks like it will support all our supported versions of PHP

2023-05-15 14:46 UTC, Sephster commented on composer.json
> +        "laminas/laminas-diactoros": "^2.24.0 || ^3.0.0",
Could we just change this to use 3.0.0?

2023-05-15 14:47 UTC, Sephster commented
Thanks for the PR @erikn69  - just some minor comments from me

2023-05-15 15:02 UTC, erikn69 commented on composer.json
> +        "laminas/laminas-diactoros": "^2.24.0 || ^3.0.0",
Yes, without problem
https://github.com/laminas/laminas-diactoros/blob/2515f4134258b1b418c23cb86606b8a09dd01aea/composer.json#L39

2023-05-15 15:05 UTC, erikn69 commented on composer.json
> +        "psr/http-message": "^1.0.1 || ^2.0",
very soon, an update is still missing for it to be available, here
https://github.com/thephpleague/uri-src/issues/108#issuecomment-1510437939

2023-05-22 09:05 UTC, Sephster commented on composer.json
> +        "laminas/laminas-diactoros": "^2.24.0 || ^3.0.0",
Awesome. Would you be able to make this change please @erikn69 and then I will merge in. If you could add a changelog entry too that would be great but if you don't, no worries. I can add in once merged. Thank you!

2023-06-06 21:32 UTC, Sephster commented on composer.json
> +        "laminas/laminas-diactoros": "^2.24.0 || ^3.0.0",
I've updated this now. Thanks

2023-06-06 21:37 UTC, merged

2023-06-15 12:26 UTC, driesvints commented
@Sephster can we maybe release this as a patch release? We're getting so much issues on Passport about this 😅

2023-06-15 12:30 UTC, driesvints commented
Thanks!