Fix including interval in response of device authorization request
thephpleague/oauth2-server pull request #1410
Opened 2024-05-22 02:24 UTC by hafezdivandari

I'm implementing device authorization flow on Laravel Passport, but when I call `$grant->setIntervalVisibility(true)` the response still doesn't include `interval`. On the response you are excluding `interval` when it's set to default 5. Although the server may use the default interval value, we still want to include the `internal` on the response.

PS: Also a typo has been fixed on `DeviceCodeRepositoryInterface`, `$deviceCodeEntity` -> `$deviceCode`

2024-07-02 09:40 UTC, Sephster commented
@hafezdivandari apologies I've not forgotten about this. My partner is sick just now and my son has a sickness bug so I have little time but will get to it as soon as she is better. Apologies for the delay. Just wanted to give you an update

2024-07-02 09:56 UTC, hafezdivandari commented
@Sephster No worries at all! Take all the time you need. I hope your family feels better soon.

2024-09-09 17:37 UTC, hafezdivandari commented
Hi @Sephster, hope you’re doing well. Any progress on the PRs related to Laravel Passport? I’ve listed them all [here](https://github.com/laravel/passport/issues/1748#issuecomment-2139157779).

2024-11-12 23:03 UTC, Sephster requested changes
Thanks for this Hafez. I think there are some bugs that have been fixed here that aren't actual bugs. I'll try to outline them as best I can below:

* Fix typo is grand. Thank you!
* For a long time I debated whether to have a "setIntervalVisibility" function. Intially I just thought we could have the default as five and if you wanted to increase or decrease this, you could set the value to something different and we'd then report it in the response as the absence of it implies 5 seconds anyway. I think this is probably why the code is the way it is now but appreciate it is confusing to set visibility and then have it do nothing. I think the easiest fix here is to change the condition that adds the interval to the response to check for if the interval visibility has been set, which should be non-breaking.
* I think it is correct to not record a new poll date if we issue a slowdown. The slowdown message just informs the client they've polled too quickly. If we logged the poll date, we'd reset the timer to 5 second again which we don't want to do.
* The interval increase of five is supposed to be followed by the client, not enforced by the server so we shouldn't need to make a change here as far as I'm aware
* Can you highlight where the issue is with us returning a slow_down after the request has been approved? I wasn't too clear where this was happening
* Because we don't need to change the interval, we shouldn't need to report new interval values so don't need to include these in the error response, and can hopefully avoid these breaking changes

Hope all this makes sense but I think we probably only need to fix the visibility honouring and the typo. Cheers for all your work on this!

2024-11-14 17:47 UTC, hafezdivandari commented on src/Exception/OAuthServerException.php
> +    public static function authorizationPending(?int $interval = null, string $hint = '', ?Throwable $previous = null): static
What if we move the `$interval` argument to the end? I can revert this change if you want, but I think it makes the polling easier for the client:

```php
do {
    sleep($interval);

    $response = Http::asForm()->post('http://passport-app.test/oauth/token', [
        'grant_type' => 'urn:ietf:params:oauth:grant-type:device_code',
        'client_id' => '<client-id>',
        'client_secret' => '<client-secret>',
        'device_code' => '<device-code>',
    ]);

    $interval = $response->json('interval'); // We use the `interval` on the error response for the next request!

} while (in_array($response->json('error'), ['authorization_pending', 'slow_down']));
```

2024-11-14 17:47 UTC, hafezdivandari commented on src/Exception/OAuthServerException.php
> +    public static function slowDown(?int $interval = null, string $hint = '', ?Throwable $previous = null): static
https://github.com/thephpleague/oauth2-server/pull/1410#discussion_r1842655405

2024-11-14 17:51 UTC, hafezdivandari commented on src/Grant/DeviceCodeGrant.php
> +                $deviceCodeEntity->setInterval($deviceCodeEntity->getInterval() + 5);
What if the client didn't? [RFC8628 section 3.5](https://datatracker.ietf.org/doc/html/rfc8628#section-3.5:~:text=but%20the%20interval%20MUST%0A%20%20%20%20%20%20be%20increased%20by%205%20seconds%20for%20this%20and%20all%20subsequent%20requests.): 

> the interval **MUST** be increased by 5 seconds for this and all subsequent requests.

If it's not enforced by the server and the server doesn't persist the new interval and doesn't validate it, what is the point of this statement then?

2024-11-14 22:26 UTC, Sephster commented on src/Grant/DeviceCodeGrant.php
> +                $deviceCodeEntity->setInterval($deviceCodeEntity->getInterval() + 5);
I've read the spec and think my interpretation is correct. It is up to the client to respect the polling interval increase, not for us to enforce it. If we sent out a slow_down error, the client should honour it by increasing its polling rate interval. The quotes above support my original post.

2024-11-14 22:27 UTC, Sephster commented on src/Exception/OAuthServerException.php
> +    public static function slowDown(?int $interval = null, string $hint = '', ?Throwable $previous = null): static
I don't think we need to include the interval and would prefer if it was removed. This would be required if the interval was being increased by the server but I believe it should stay static.

2024-11-14 22:28 UTC, Sephster commented on src/Exception/OAuthServerException.php
> +    public static function authorizationPending(?int $interval = null, string $hint = '', ?Throwable $previous = null): static
Thanks for reverting Hafez. I think it is useful if the interval value changes as it did in the original implementation but when this is not the case, I think it loses its value and we are safe to omit it. Thanks for making this change.

2024-11-14 22:30 UTC, hafezdivandari commented on src/Grant/DeviceCodeGrant.php
> +                $deviceCodeEntity->setInterval($deviceCodeEntity->getInterval() + 5);
But the first statement says that client must respect the polling interval REQUIRED by the "slow_down" error, how we expect the client respect anything when we don't **require** it?

2024-11-14 22:37 UTC, hafezdivandari commented on CHANGELOG.md
> +- Fixed bug on setting interval visibility of device authorization grant (PR #1410)
Sure, I'll fix this when all changes are confirmed.

2024-11-14 23:07 UTC, Sephster commented on src/Grant/DeviceCodeGrant.php
> +                $deviceCodeEntity->setInterval($deviceCodeEntity->getInterval() + 5);
I understand what you are saying and the RFC is not worded very well but I'm pretty certain this is up to clients to implement, not the server. The server is issuing the slow_down command which tells the client it must increase the polling interval by 5. There is nothing to dictate we need to check this on the server side  and I think it needlessly complicates the code base to do so. 

If there are repeat violations of polling intervals, implementations can handle this however they wish. It should be reasonably easy to detect if the polling interval hasn't been increased by 5 as we would see multiple violations.

2024-11-14 23:12 UTC, hafezdivandari commented on src/Grant/DeviceCodeGrant.php
> +                $deviceCodeEntity->setInterval($deviceCodeEntity->getInterval() + 5);
reverted.

2024-11-14 23:35 UTC, hafezdivandari commented on CHANGELOG.md
> +- Fixed bug on setting interval visibility of device authorization grant (PR #1410)
Fixed.

2024-11-15 14:12 UTC, hafezdivandari commented
@Sephster I've applied the requested changes, please review again.

2024-11-26 19:21 UTC, hafezdivandari commented
@Sephster Just a kind reminder for this.

2024-12-03 23:23 UTC, Sephster requested changes

2024-12-03 23:23 UTC, Sephster commented on src/Grant/DeviceCodeGrant.php
> +        private readonly int $defaultInterval = 5
I'm keen to avoid breaking changes if possible and I think this is one we can avoid. The default interval provided by the library is 5 seconds, but once overridden via this argument, it is no longer the default so I think the original name should stand.

It could be argued that this value is the default interval set by the implementers code. In that case, there might be more of an argument for adding the word "default" but as it shouldn't change once set, it feels a bit superfluous. Is it possible to role this name change back? Thank you

2024-12-03 23:23 UTC, Sephster commented on src/Repositories/DeviceCodeRepositoryInterface.php
> +        string $deviceCode
This is the correct change but feels off to issue a new major for one argument change. Unfortunately that is the nature of PHP these days. Can you think of any way to avoid this? I've been thinking this over and can't really think of anything. Did think of marking this function as deprecated to point implementers to a correctly named function but doesn't get around the fact that this is a typo that wasn't spotted during the RC. Any input would be greatly appreciated here

2024-12-03 23:31 UTC, hafezdivandari commented on src/Grant/DeviceCodeGrant.php
> +        private readonly int $defaultInterval = 5
is `readonly` ok, or I should revert that too? I think it's good to have `readonly` in order to avoid mutation in future!

2024-12-03 23:33 UTC, hafezdivandari commented on src/Repositories/DeviceCodeRepositoryInterface.php
> +        string $deviceCode
This is very unlikely that one pass this as a named argument IMO, and implementing an interface method with different arg names is not forbidden AFAIK.

2024-12-03 23:46 UTC, hafezdivandari commented on src/Repositories/DeviceCodeRepositoryInterface.php
> +        string $deviceCode
I reverted this, as I don't want to delay merging this PR anymore. We can fix the typo later.

2024-12-20 22:31 UTC, merged