Fix scope on device code grant
thephpleague/oauth2-server pull request #1412
Opened 2024-05-23 11:27 UTC by hafezdivandari

Fixes #1411

2024-09-18 19:41 UTC, Sephster commented
@hafezdivandari sorry for the radio silence. I will aim to look at the PRs this week

2024-09-18 19:51 UTC, hafezdivandari commented
Thank you @Sephster

2024-09-25 20:37 UTC, hafezdivandari commented
@Sephster just a reminder after a week...

2024-09-25 21:52 UTC, Sephster commented
Sorry I've had an emergency in my work I've been dealing with since Thursday. Will get on this as soon as complete

2024-10-08 14:05 UTC, ezequidias commented
@Sephster just a reminder after two weeks...

![Capturar_select-area_20241008110439](https://github.com/user-attachments/assets/10ac2fb8-cdbf-443f-b999-e89f0798f101)

2024-10-27 23:37 UTC, Sephster requested changes

2024-10-27 23:49 UTC, hafezdivandari commented on examples/src/Repositories/DeviceCodeRepository.php
> +        foreach ($scopes as $scope) {
last poll and scopes are persisted on the DB and retrieved back later just like other attributes. We are just fixing the example here.

2024-10-27 23:55 UTC, hafezdivandari commented on tests/Grant/DeviceCodeGrantTest.php
> +            'device_code'   => $deviceCodeEntity->getIdentifier(),
We send the identifier here, there is no encryption / decryption involved on device code (unlike auth code on "authorization grant") the device:

* `respondToAccessTokenRequest` calls `validateDeviceCode`
* `validateDeviceCode` calls `getDeviceCodeEntityByDeviceCode` with this identifier.

2024-10-27 23:55 UTC, hafezdivandari commented on tests/Grant/DeviceCodeGrantTest.php
> +            'device_code' => uniqid(),
https://github.com/thephpleague/oauth2-server/pull/1412/files/7570854ff9b31f1d7da77c0611324b76c714fb8c#r1818218785

2024-10-27 23:55 UTC, hafezdivandari commented on tests/Grant/DeviceCodeGrantTest.php
> +            'device_code'   => uniqid(),
https://github.com/thephpleague/oauth2-server/pull/1412/files/7570854ff9b31f1d7da77c0611324b76c714fb8c#r1818218785

2024-10-27 23:55 UTC, hafezdivandari commented on tests/Grant/DeviceCodeGrantTest.php
> +            'device_code'   => uniqid(),
https://github.com/thephpleague/oauth2-server/pull/1412/files/7570854ff9b31f1d7da77c0611324b76c714fb8c#r1818218785

2024-10-27 23:56 UTC, hafezdivandari commented on tests/Grant/DeviceCodeGrantTest.php
> +                'device_code'   => $deviceCode->getIdentifier(),
https://github.com/thephpleague/oauth2-server/pull/1412/files/7570854ff9b31f1d7da77c0611324b76c714fb8c#r1818218785

2024-10-28 00:00 UTC, hafezdivandari commented on examples/src/Repositories/DeviceCodeRepository.php
> +        $deviceCodeEntity->setLastPolledAt(new DateTimeImmutable());
> The last polled date is set when the client tries to retrieve an access token.

It's true but then we persist the last poll into the DB, so the next time the client tries to retrieve an access token we should get the last poll from the DB to be able to validate the device code!

2024-10-28 21:18 UTC, hafezdivandari commented on tests/Grant/DeviceCodeGrantTest.php
> +            'device_code'   => $deviceCodeEntity->getIdentifier(),
I fixed the encryption of the device code, it was totally missed!

2024-11-04 22:10 UTC, hafezdivandari commented on tests/Grant/DeviceCodeGrantTest.php
> +            'device_code'   => $deviceCodeEntity->getIdentifier(),
@Sephster ?

2024-11-11 11:26 UTC, Sephster commented on CHANGELOG.md
> +- Fixed bug where scopes where not set on access token when using device authorization grant (PR #1412)
suggestion merged

2024-11-11 11:27 UTC, Sephster commented on examples/src/Repositories/DeviceCodeRepository.php
> +        foreach ($scopes as $scope) {
examples no longer edited so this comment is no longer applicable.

2024-11-11 11:31 UTC, Sephster commented on tests/Grant/DeviceCodeGrantTest.php
> +            'device_code' => uniqid(),
confirmed changed.

2024-11-11 11:32 UTC, Sephster commented on tests/Grant/DeviceCodeGrantTest.php
> +            'device_code'   => uniqid(),
confirmed changed

2024-11-11 11:32 UTC, Sephster commented on tests/Grant/DeviceCodeGrantTest.php
> +                'device_code'   => $deviceCode->getIdentifier(),
confirmed changed.

2024-11-11 11:32 UTC, Sephster commented on examples/src/Repositories/DeviceCodeRepository.php
> +        $deviceCodeEntity->setLastPolledAt(new DateTimeImmutable());
examples no longer updated in this PR so original comment no longer applies

2024-11-11 11:42 UTC, Sephster commented on tests/Grant/DeviceCodeGrantTest.php
> +            'device_code'   => $deviceCodeEntity->getIdentifier(),
Sorry, that's my bad. I forgot we don't encrypt the device code. Is there a benefit to doing this? For the auth code, it makes sense as the payload is static so we avoid hitting the DB, but because of the polling needed on the device code grant, we can't avoid hitting the DB so the encryption benefits largely diminish.

I can't see an immediate benefit to encrypting this information but might be overlooking something. If not, for simplicity it might be worth keeping as is already

2024-11-11 11:50 UTC, hafezdivandari commented on tests/Grant/DeviceCodeGrantTest.php
> +            'device_code'   => $deviceCodeEntity->getIdentifier(),
It seems more secure, as we use the same pattern on refresh token and auth code, we never expose the real ID. It's also easier to validate the device code this way than relying on the DB values.

2024-11-12 22:10 UTC, Sephster commented on tests/Grant/DeviceCodeGrantTest.php
> +            'device_code'   => $deviceCodeEntity->getIdentifier(),
I think the encryption should be reverted. I'm happy to do this if you like as appreciate you spent time on this but I think it offers little. The comms are sent over TLS/SSL so are encrypted out the box and the device ID is already a random 40 character string that should be un-guessable. We allow people to increase the length of this if they wish as well to make it even harder to brute force.

Because of this, I think we should just keep the code simple and remove the encryption. Once this is done, I'll merge in this PR as it looks good to go to me. Thanks @hafezdivandari and sorry to be a pain

2024-11-12 22:16 UTC, hafezdivandari commented on tests/Grant/DeviceCodeGrantTest.php
> +            'device_code'   => $deviceCodeEntity->getIdentifier(),
@Sephster done.

2024-11-14 22:40 UTC, Sephster commented on tests/Grant/DeviceCodeGrantTest.php
> +            'device_code'   => $deviceCodeEntity->getIdentifier(),
thank you!

2024-11-14 22:44 UTC, Sephster approved these changes

2024-11-14 22:52 UTC, merged