sort require & opt. example
thephpleague/oauth2-server pull request #1462
Opened 2024-11-26 14:05 UTC by xerc

2024-12-04 00:19 UTC, Sephster requested changes
Thanks for your PR. Just a few minor comments from me then should be good to merge. Thank you

2024-12-04 00:19 UTC, Sephster commented on README.md
> +https://github.com/thephpleague/oauth2-server/blob/7b9ec37d5077c0382aa3748c6e125c5408d5adb9/composer.json#L7
I think the previous format is preferable as the readme should be easily accessible. I think this change reduces that

2024-12-04 00:19 UTC, Sephster commented on composer.json
> +        "php": "^8.1 || ^8.2 || ^8.3 || ^8.4",
please can we revert this change? I can't remember the reasons why but we did have the constraint as ^8.0 at one point but it was reverted to ~. I think we will change to just ^9.0 when a new major PHP ver is released.

2024-12-20 22:12 UTC, Sephster commented
Closing as not essential and no further updates from author

2024-12-20 22:12 UTC, closed without merging

2024-12-21 19:06 UTC, xerc commented
@Sephster didnt you see my comments @ https://github.com/thephpleague/oauth2-server/pull/1462/files/a9b9429d26b41b5d594b615a7bfcbf68584cd688#r1868528200 ?