Fix Events and add TODOs for the next major release
thephpleague/oauth2-server pull request #1467
Opened 2024-12-10 11:39 UTC by hafezdivandari

Related to #1465 

* Fixed a bug where "Device Authorization" grant emits wrong events after access / refresh token is issued.
* No event is emitted on "Implicit" grant after an access token is issued, unlike other grants! 
    * This can't be fixed without changing the method signature which is a BC breaking change.
    * Added a TODO comment to be fixed on the next major release.
* Added a TODO comment to fix a typo on the argument name of the `\League\OAuth2\Server\Repositories\DeviceCodeRepositoryInterface::getDeviceCodeEntityByDeviceCode()` method on the next major release: `string $deviceCodeEntity` -> `string $deviceCode`

2024-12-20 22:35 UTC, Sephster requested changes
Thanks for this @hafezdivandari and thanks for your ongoing work with the library. Would it be possible to add a test for the event emissions and a changelog entry? If you don't have time I can take a look at this. Thank you

2024-12-20 22:53 UTC, hafezdivandari commented
Sure @Sephster I'll take complete this asap.

2024-12-29 21:03 UTC, hafezdivandari commented
@Sephster a changelog entry and tests for events have been added.

2025-02-06 22:26 UTC, hafezdivandari commented
@Sephster please don't forget about this one, before release, thanks.

2025-02-14 12:04 UTC, Sephster commented
Will be looking at this tonight/this weekend to get a new release tagged

2025-02-14 22:21 UTC, Sephster approved these changes
Looks good. Thanks @hafezdivandari

2025-02-14 22:21 UTC, merged